name: Build

on:
  pull_request:
    branches: [ 2.x ]
  push:
    branches: [ 2.x ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [10.x, 12.x, 14.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: npm i

      - name: Lint the code
        run: npm run lint

      - name: Run test
        run: npm run test
