# This workflow receives event from paper-handlebars (on release created) and create a PR to bump version

on:
  repository_dispatch:
    types: [bump_hbs]

jobs:
  bump-paper-handlebars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump version
        env:
          VERSION: ${{ github.event.version }}
        run: sed "s/\(\"@bigcommerce\/stencil-paper-handlebars\":\s+\"\)\d+\.\d+\.\d+/\1$VERSION\2/g" package.json
      - run: echo $NOTES
        env:
          NOTES: ${{ github.event.notes }} 
      - name: Test
        run: cat package.json
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          commit-message: Bump paper handlebars version
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: bump-paper-handlebars
          delete-branch: true
          title: 'fix: Bump Paper Handlebars' # todo set appropriate commit type
          body: |
            
            - Bump Paper Handlebars
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: 
            automated pr
          team-reviewers: |
            owners
            maintainers
          draft: false
          