name: Paper Library Semantic Release

on:
  push:
    branches: [master, main]


jobs:
  release:

    permissions:
      contents: write 
      issues: write
      pull-requests: write
      id-token: write
      packages: write
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '22.x'
      - run: npm i -g npm@latest
      - run: npm i
      - name: Check Git Commit name
        run: git log -1 --pretty=format:"%s" |  npx commitlint
      - name: Deploy to npm and git
        run: npm config list && npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GA_USERNAME: ${{ secrets.PAT_USERNAME }}
          GA_TOKEN: ${{ secrets.PAT_TOKEN }}
